### ISSUE TITLE
Can't create task with timestamp as due date

### ISSUE THREAD

**Issue by HeikoAdams** [cinatic/taskwhisperer#1]
When trying to create a taks with a timestamp as due date the extension allways says "an error occured"

**Comment by cinatic** [comment]
i don't know if you are familiar with TaskWarrior but you have to specify the correct timeformat in your ~/.taskrc

e.g. mine for german is

```
# Formats 
dateformat=D.M.Y H:N
```

please check also your log file /var/log/messages.log you should get an detailed error message.

i should really pass through the original error message

**Comment by HeikoAdams** [comment]
Looks correct to me
![bildschirmfoto von 2016-02-16 18-50-12](https://cloud.githubusercontent.com/assets/1418818/13085355/21a4e1a4-d4de-11e5-9298-fee9f8beb833.png)

**Comment by HeikoAdams** [comment]
I'm running Fedora 23 and there is no /var/log/messages.log file

**Comment by HeikoAdams** [comment]
gnome-log has the following error message after trying to create a new task with due timestamp:

> '18.02.2016 20:15' is not a valid date in the 'Y-M-D' format.

**Comment by cinatic** [comment]
I assume you don't have added a date format in your **~/.taskrc** that's why TaskWarrior is using the default format which is "Y-M-D". 

Either add your desired format to your taskrc or try it with 2016-02-18 (Y-M-D).

```
# Formats 
dateformat=D.M.Y H:N
```

**Comment by HeikoAdams** [comment]
If I use that Y-M-D format it works fine. 

But passing through the original error message would also be a good idea :wink:
