### ISSUE TITLE
Manual installation failing

### ISSUE THREAD

**Issue by jose1711** [cinatic/taskwhisperer#105]
Trying to manually install the extension under Gnome-shell 42.0:
```
apr 25 21:20:26 myhost gnome-shell[18075]: JS ERROR: Extension taskwhisperer-extension@infinicode.de: GLib.FileError: Failed to open file „/home/jose/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/schemas/gschemas.compiled“: open() failed: File or directory does not exist

```

**Comment by cinatic** [comment]
i updated the installation instruction

#### Git master

Checkout and run `make install`, a locale copy will be generated in (~/.local/share/gnome-shell/extensions/).
Maybe a restart of GNOME Shell is needed and/or enabling the extension.

```
git clone https://github.com/cinatic/taskwhisperer.git && cd taskwhisperer && make install
```

#### Git Release

Download [latest release](https://github.com/cinatic/taskwhisperer/releases/latest/download/taskwhisperer-extension.zip) and extract it to ***~/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/***.
Maybe a restart of GNOME Shell is needed and/or enabling the extension.

```
mkdir -p ~/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/ && curl -L https://github.com/cinatic/taskwhisperer/releases/latest/download/taskwhisperer-extension.zip | bsdtar -xf - -C ~/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/
