### ISSUE TITLE
GNOME 43 Support

### ISSUE THREAD

**Issue by mmusgrov** [cinatic/taskwhisperer#107]
This excellent extension does not work on the latest GNOME 43 (Guadalajara) (which was released on 21 September 2022).

**Comment by cinatic** [comment]
please check logs for errors `journalctl /usr/bin/gnome-shell` and provide more details about your environment distro

**Comment by mmusgrov** [comment]
My mistake: I recently upgraded to gnome 43 but then upgraded taskwhisperer using the "Generic (Local installation) method by Moving files into your locale extension directory" but I wasn't able to enable it since gnome-tweak-tool isn't available on my distro (Fedora release 37).

But now I've just upgraded using the official mechanism: install via install button -> https://extensions.gnome.org/extension/1039/taskwhisperer/

My apologies for not using the EGO (extensions.gnome.org) install mechanism.
