### ISSUE TITLE
TaskWhisperer not compatible with Gnome 44

### ISSUE THREAD

**Issue by RMStyle** [cinatic/taskwhisperer#108]
TaskWhisperer is not compatible with the version 44 of Gnome. After upgrading to the latest version, the extension can not be enabled.

![image](https://user-images.githubusercontent.com/36329720/234720170-9f0fdaf5-e147-438c-a2ea-eb42c5d064c3.png)

**Comment by jpritikin** [comment]
I added version 44 to the list. See:

```
.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/metadata.json
```

```
  "shell-version": [
    "40",
    "41",
    "42",
    "43", "44"
  ],
```

I have no idea if any other fix is need, but everything still seems to work well enough.

**Comment by RMStyle** [comment]
That does the trick. It works again, maybe worth to make a new release with it, since Gnome 44 is getting rolled out on more and more distros.
