### ISSUE TITLE
Not compatible with Gnome 45

### ISSUE THREAD

**Issue by mcaliandro** [cinatic/taskwhisperer#109]
Hi all, recently I update my system to Gnome Shell 45 and TakWhisperer stopped to work. I tried to modify `metadata.json` by adding the newer release to the list of supported Gnome versions, as follows:

`~/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de`
```json
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Taskwhisperer is a extension for TaskWarrior Application https://taskwarrior.org. It is to display upcoming tasks and task details as well as to create and modify them.\n",
  "gettext-domain": "gnome-shell-extension-taskwhisperer",
  "localedir": "/usr/local/share/locale",
  "name": "TaskWhisperer",
  "settings-schema": "org.gnome.shell.extensions.taskwhisperer",
  "shell-version": [
    "40",
    "41",
    "42",
    "43",
    "44",
    "45"
  ],
  "url": "https://github.com/cinatic/taskwhisperer",
  "uuid": "taskwhisperer-extension@infinicode.de",
  "version": 26
}
```

Then, I logged out and in again the Gnome session to reload the extension but it fails due to the following error:

![Screenshot from 2023-10-20 15-22-37](https://github.com/cinatic/taskwhisperer/assets/44460601/0a08be60-da8a-44a2-a941-9394889df1d7)
![Screenshot from 2023-10-20 15-23-05](https://github.com/cinatic/taskwhisperer/assets/44460601/5eb5fdf9-cdb5-4e73-83af-541937adb7df)

**Comment by cinatic** [comment]
review is in progress, you can test the latest version if you like:

[taskwhisperer-extension.zip](https://github.com/cinatic/taskwhisperer/files/13056231/taskwhisperer-extension.zip)
