### ISSUE TITLE
SyntaxError: JSON.parse: unexpected non-whitespace character

### ISSUE THREAD

**Issue by akosiaris** [cinatic/taskwhisperer#13]
/var/log/syslog says:

```
Gjs-CRITICAL **: JS ERROR: SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data @ /home/alex/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/taskService.js:122
```

Just installed the extension, not sure how to report on which "version" I am on.

**Comment by cinatic** [comment]
Hi & Thanks for the bug report!

Could you give me the output of this cmd:
task status:Pending export

if you have installed it via extensions.gnome.org then i assume you have the old version, the new version is in review process.

**Comment by cinatic** [comment]
Or you can also just check if it is wellformed JSON (Missing commas, missing [ ] brackets at start & end). If you notice a difference between those commands:

task status:Pending export
task rc.json.array=on status:Pending export

Then you need add json.array=on in your ~/.taskrc

**Comment by akosiaris** [comment]
I 've installed it via extensions.gnome.org indeed, so old version it is. Metadata.json has 1 in the "version" key if that helps.

The diff of the 2 commands you proposed obviously is the [ ] JSON array syntax. So the json.array=on config stanza in my ~/.taskrc did indeed help somewhat, I was "upgraded" to a new error

```
gnome-session[1346]: (gnome-shell:1487): Gjs-WARNING **: JS ERROR: TypeError: a.Due is undefined
gnome-session[1346]: TaskWhispererMenuButton<.reloadTaskData/</<@/home/alex/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:221
gnome-session[1346]: TaskWhispererMenuButton<.reloadTaskData/<@/home/alex/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:219
gnome-session[1346]: readCB@/home/alex/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/taskService.js:128
```

Want me to close this issue and file this as a new issue or want to continue on this one ?

**Comment by cinatic** [comment]
Okay great, the other one has already been filed as a bug and was fixed with the new version. 

This happens if Tasks has been added without a due date. If you want to use the extension just remove the old files from the extension directory (maybe ~/.local/share/gnome-shell/extension) and replace it with the new files. But you can also wait for the new version @ gnome.org, i commited the new files yesterday so usually it should be published in 1-2 Days

**Comment by cinatic** [comment]
The new version has been reviewed and published so you are able to update now via gnome.org
