### ISSUE TITLE
Page system when there are many tasks to display

### ISSUE THREAD

**Issue by unixfox** [cinatic/taskwhisperer#15]
I'm facing to a problem, I can't modify my tasks because I've many pending tasks and the list fills all my middle screen:
![](http://img15.hostingpics.net/pics/895292problemtaskwhisperer.png)

Is it possible to integrate a page system like [1], [2], etc ?
![](https://i.unixfox.eu/17-20-17-2016.png)

**Comment by cinatic** [comment]
Hey =),

i already have a scroll & scroll loading functionality which i use in my neingag extension. Do you think that this has some disadvantages? I can't imagine that there are people with much more then 100 tasks, so scroll loading á 50 items per page should be ok IMO?

Even if someone has e.g. 500 tasks so he has to scroll down a little bit which works really flawless & fast

**Comment by unixfox** [comment]
Your scroll system is interesting, I think that's a great idea. I don't really know which is the best: scroll or page.

**Comment by cinatic** [comment]
is implemented in the new version, there is still a really tiny thing with scrolling due of the ScrollView inside the PopupSubMenu, scrolling stops when cursor is inside a submenu. I will fix this later by creating a own Menu Object.

**Comment by unixfox** [comment]
Wow I love the new version, great job !

**Comment by cinatic** [comment]
ty
