### ISSUE TITLE
Sort tasks by urgency

### ISSUE THREAD

**Issue by HeikoAdams** [cinatic/taskwhisperer#17]
It would be more helpfull if the tasks would by sorted by urgency instead of due-date. This could also be done as an option so everyone can decide if he wants chronlogical sorting or sorting by urgency.

**Comment by cinatic** [comment]
I will implement sorting icons, the default sort order will be the due-date. As soon as settings are implemented the default sort order can be customized.

**Comment by cinatic** [comment]
sorting can be changed by flag or clock icon
