### ISSUE TITLE
Date format in Create and Modify, add project and priority

### ISSUE THREAD

**Issue by ghost** [cinatic/taskwhisperer#22]
Hi.

currently your extension only supports Y-M-D and not **Y-M-D H:M**. Setting the time is important. I always get false date format if if try to modify it to e.g. 10am or create a task with 2016-07-13 10:00 or even 1000 should work (faster without the :).

Also due:'2016-07-13 00:00' should be displayed and not  due:'13.07.2016 00:00', otherwise modifying a task requires inverting those values manually.

A direct input of project and priority (or +- for those in detail view) should also be possible.

Can you look into this? Really good extension though.

Thanks in advance. :+1: 

Varakh

**Comment by cinatic** [comment]
Hi Varakh,

you need to specifiy the correct date in your config (~/.taskrc)
http://linux.die.net/man/5/taskrc

for example, as a german i configured this:

# Formats
dateformat=D.M.Y H:N

#CAVEAT
Did you know you can also add things like +1d, +1w?

Thanks for using the extension, have a nice day

**Comment by ghost** [comment]
Ok, thanks.
