### ISSUE TITLE
minor: task fields don't scale with Gnome's scaling factor

### ISSUE THREAD

**Issue by Coleej** [cinatic/taskwhisperer#24]
Its a tiny bug. If you change the scaling factor with gnome's tweak tool, the font of a task will scale but the field's height won't. Some characters end up getting cut off, e.g. the tails of y's or p's

**Comment by cinatic** [comment]
i removed the fixed heights and it looks better now, unfortunetly the cell content is "overflow ellipsis" and i was not able to change it, but i will change the layout in an another update
