### ISSUE TITLE
Changing date / time isn't working great

### ISSUE THREAD

**Issue by metal3d** [cinatic/taskwhisperer#26]
I created a task for today, then I want to change "due".

I clicked "modify task", and a popup displays:

"due:'04.10.2016 00:00' description:'My Task description'"

Without to change anything, save button says that the date isn't well formatted (not Y-M-D).

I changed date to the right format and changed hour -> hour is still 00:00.

BTW: nice extension - working with taskwarrior was the thing to do, congrat !

**Comment by cinatic** [comment]
hi,

you need to specifiy the correct date format in your config (~/.taskrc)
http://linux.die.net/man/5/taskrc

for example, as a german i configured this:

# Formats

dateformat=D.M.Y H:N

#CAVEAT
You can also add things like +1d, +1w?

Thanks for using the extension, have a nice day
