### ISSUE TITLE
Manual install should mention that you must rename folder to uuid name

### ISSUE THREAD

**Issue by ghost** [cinatic/taskwhisperer#27]
I cloned taskwhisperer in ~/.local/share/gnome-shell/extensions/taskwhisperer
It did not appear in tweak tool.
It works with this path: ~/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de

Should probably be mentioned in Readme.

**Comment by cinatic** [comment]
thanks, i placed a note into readme
