### ISSUE TITLE
Graphical issues with some Gnome themes

### ISSUE THREAD

**Issue by fbruetting** [cinatic/taskwhisperer#28]
Here is a screenshot with using the Adapta theme, could you please correct this? Thanks for the extension!

![menu_023](https://cloud.githubusercontent.com/assets/10520767/21396159/7a5d4a5c-c79f-11e6-8b2b-12dba613c000.png)

**Comment by cinatic** [comment]
Hm shit, well thanks, i am not sure if i can influence the color of the svg
images by css. but i will find a solution! Thanks for the report

2016-12-21 17:04 GMT+01:00 Frank <notifications@github.com>:

**Comment by MacLotsen** [comment]
It also appears in the [Arc theme](https://github.com/horst3180/arc-theme) unless you use Arc-Dark as shell theme. Using the verison from 2017-03-02

**Comment by cinatic** [comment]
i tried several things, but it looks like the color of svg can not be changed so i will add a dark theme soon which can be selected in the settings, thx for report

**Comment by cinatic** [comment]
added now a setting which will use dark background and dark icons.

i will change the layout again as soon as i have implemented a own MenuItem
