### ISSUE TITLE
Tasks added via command line do not appear

### ISSUE THREAD

**Issue by harmancode** [cinatic/taskwhisperer#29]
I add a task via command line. It appears in the task list when I check via command line. But it does not appear in this extension's list. Is this normal? Do they have separate lists?

**Comment by cinatic** [comment]
Per user it should be the same "database".

Those are the commands executed by the service:

task rc.json.array=on status:pending export

or if you clicked on completed only:

task rc.json.array=on status:completed export

do you get some output with them?

**Comment by harmancode** [comment]
Yes I get this output with the 1st command:
```
$ task rc.json.array=on status:pending export
[
{"id":1,"description":"Test Gnome extension","due":"20170110T210000Z","entry":"20170110T165846Z","modified":"20170110T170159Z","status":"pending","uuid":"b44a0a63-46c1-40ee-946e-63e5f9749558","urgency":"8.72496"}
]
Configuration override rc.json.array:on
```

**Comment by cinatic** [comment]
The extension will use the same output to display the tasks. Do you use the same user in your shell as for login to gnome?

e.g. if you add tasks as root or some other user the items will not be displayed in the extension

**Comment by harmancode** [comment]
Yes, I use the same user when creating tasks and using the extension. This is Gnome 3.14.1, debian 8.6, taskwarrior v2.3.0.

I did some more tests. I realized that when I use a due:tomorrow or due:2017-01-11 argument it does not shown in the extension's list.

Moreover, total task amount shown is not correct. It appears in Gnome Panel as just 2 now, however it shows 5 tasks, and I have 8 tasks in cmd line's list. The three tasks which have a due date are not shown in extension's list.

**Comment by cinatic** [comment]
Thanks for your input, i think data which has no due with time or completely no due are not parsed, i will add some enhancements here in the next version.

Can you try to verify this by adding a due like due:2017-01-11 11:00

**Comment by turbovan** [comment]
I have been testing out the taskwhisperer extension and for me it is working fine. I can add tasks from the command line and they appear in the extension. I can use various due date formats when adding the task like tom for tomorrow, wed, thu etc. and they work fine. All tasks show correctly in the extension with due dates.

I am however using arch linux, with gnome 3.22 and Task Warrior 2.5.1 so maybe the JSON output handling has been improved in later versions of Task Warrior. I saw a number of JSON improvements in the Task Warrior release notes but not this specific issue.

**Comment by cinatic** [comment]
@turbovan thx for testing
