### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by ghost** [cinatic/taskwhisperer#31]
Thanks for this extension, are any of the following requests possible?

- [x] Option to select: Task number in the panel or the Taskwarrior icon.
- [x] Add "Undo" option.
- [x] Some layout adjustments to facilitate access to the "done" option ([something like this](https://cloud.githubusercontent.com/assets/20990110/23801364/e4254888-057d-11e7-943a-65f0aabb7b13.png))

**Comment by cinatic** [comment]
i like 1 and 3 will take this into account for the next release

Where would you like to have an undo option?

**Comment by ghost** [comment]
The best option would be in the completed task tab, [no](https://cloud.githubusercontent.com/assets/20990110/23803203/c899c264-0583-11e7-8a90-1725bbd05de8.png)?

**Comment by cinatic** [comment]
I see, as an opposite of the complete icon okay

CitDub <notifications@github.com> schrieb am Fr., 10. März 2017, 17:22:
