### ISSUE TITLE
Option to change dateformat?

### ISSUE THREAD

**Issue by bios-ben** [cinatic/taskwhisperer#38]
I see in issues #22 and #26 you've fixed the problem with date format by setting `dateformat=D.M.Y H:N` inside .taskrc ... this allows editing to work

Is it possible to get the edit page to allow other formats? I'd like to use the standard ISO Y-M-D format instead of this German ordering it seems to be set to.

The same goes for the display of the due date display time, is there any way to change this format?

![image](https://user-images.githubusercontent.com/9565755/28145811-08828de0-672a-11e7-9dec-1e90dd3ddf81.png)

**Comment by cinatic** [comment]
Thanks for the report.

I don't do any format validation inside the extension! What you enter will be passed 1 by 1 to task warrior. You can verify this by adding the task manually in your shell.

You need to enter the date format in the format  you set in your .taskrc config. Afaik ISO style is used when no dateformat is specified.

Regarding the display format I will add a setting for it in the upcoming version.

**Comment by cinatic** [comment]
OK I see, there is another issue here.

The preset value in the input field will always be the german fomat I will change this behaviour

**Comment by bios-ben** [comment]
Excellent, I understand that it passes it directly to taskwarrior, so it's important that "due:XXXX" is in whatever the .taskrc dateformat expects, or you get an error as others have reported. So the bug here just to confirm is that the edit will have "due:german format" yet but default be expecting "due:ISO format" and people get an error ... if you make the "due:" on edit match whatever .taskrc expects, we're golden! 


As for the display format of a long date "July 7, 2017 10:00 PM" type customization would be awesome, if that's what you mean will be coming in a future version. I look forward to it! 

----- Original Message -----

**Comment by cinatic** [comment]
Right, so atm if you edit a task it will workin general but you need change
the time to right format every time...

1. I will check if we can globally use the value from .taskrc for dates

2. Add additional date format for display dates

Ben <notifications@github.com> schrieb am Do., 13. Juli 2017, 09:19:

**Comment by cinatic** [comment]
you can set the date format now in settings, it will use the settings overwrite function of taskwarrior. However if no format is set it takes the default from the .taskrc.
