### ISSUE TITLE
Tasks without a due date show up at the top

### ISSUE THREAD

**Issue by gsauthof** [cinatic/taskwhisperer#39]
When I select the clock-icon, the extension puts tasks without any due date at the top of the list, even before tasks with a due date in the past. They are also marked as important (with an orange symbol).

Expected behavior:
Tasks without a due date are ordered after any task that has a due date (and aren't marked as important).

This is also how the task command works when you sort by due date, e.g. via a config line like

    report.due.sort        = due

and then calling

    $ task due

**Comment by cinatic** [comment]
added a setting for it
