### ISSUE TITLE
Add buttons for starting and stopping tasks

### ISSUE THREAD

**Issue by HeikoAdams** [cinatic/taskwhisperer#4]
Having buttons to start and stop a task would be nice because currently this has to be done from terminal

**Comment by cinatic** [comment]
Are you use this to track time or something?

**Comment by HeikoAdams** [comment]
Not ATM because I'm just starting using taskwarrior but in the future it might be

**Comment by excieve** [comment]
I'd like this feature too — using it for timetracking with a Taskwarrior hook.

**Comment by cinatic** [comment]
it is a little bit pitty that taskwarrior does not provide a own time tracking functionality.

Also for my own interest i would like to implement something, which can display the worked time and maybe more data like estimation. Which hook are you using?

**Comment by excieve** [comment]
@cinatic Yeah, built-in timetracking would've been great. I'm currently using [this one](https://gist.github.com/wbsch/d977b0ac29aa1dfa4437) as it provides a ledger-compatible output, which makes reporting easier.

**Comment by pacoqueen** [comment]
I think [this pull request](https://github.com/cinatic/taskwhisperer/pull/33) solves the issue. Not the tracking functionality, but the start/stop button one.

**Comment by cinatic** [comment]
it's merged thx @pacoqueen, extension is currently in review
