### ISSUE TITLE
Doesn’t work with Gnome 3.24.3

### ISSUE THREAD

**Issue by fbruetting** [cinatic/taskwhisperer#40]
Several icons with three dots show up in the top bar, and it doesn’t work at all.

![bildschirmfoto von 2017-09-01 11-00-10](https://user-images.githubusercontent.com/10520767/29962816-cbf2ef3e-8f04-11e7-8a72-d436c3d45e84.png)

**Comment by cinatic** [comment]
hello @fbruetting 

wow never seen that.

Can you tell me which gnome theme and system do you use? Did you changed anything or just installed the extension? 

Have you already tried to remove and reinstall it?

**Comment by cinatic** [comment]
or a try to reload gnome-shell with ALT+F2 and then type r + enter

**Comment by fbruetting** [comment]
I had to remove it manually by deleting the folder since the switch in gnome-tweak-tool is greyed out and an attention mark is shown. I run Fedora 26 on Wayland, so no shell restart. Shell is 3.24.3, as is Gnome.

Looking glass displays the following many times:
```
GLib.SpawnError: Kind process <task> could not be started (no such file or directory)
TypeError: TaskWhispererMenu is undefined
```

So it seems to be due to me not having taskwarrior installed, yet. Think you haven’t done proper exception handling.

// And I assume all these icons to be created when returning from locked screen etc., where all the extensions are restarted. But if something fails, no icon should be created at all.

**Comment by cinatic** [comment]
Yes that makes sense. I agree the error handling espacially in this case is an important thing to do otherwise new users will be confused.

Thanks for the details

**Comment by fbruetting** [comment]
No problem, but it seems that it hasn’t anything to do with Gnme 3.24.3, should’ve checked this first. ;)

**Comment by fbruetting** [comment]
Ok, works fine if task is installed…
