### ISSUE TITLE
TaskWarrior icon appears after resuming the desktop session

### ISSUE THREAD

**Issue by mart-w** [cinatic/taskwhisperer#41]
After the screen was locked or after logging in in general, the TaskWarrior icon appears in the panel, even if disabled in the extension’s settings. When the settings window is opened, the icon disappears instantly.

I am running Ubuntu GNOME 16.04.3 64-bit with GNOME 3.18.5 and TaskWhisperer version 9.

**Comment by mart-w** [comment]
The problem seems to generally occur when the GNOME shell is reloaded – reloading it by sending the `r` command in the Alt-F2 prompt also causes it to happen.

**Comment by cinatic** [comment]
thanks for the report!
