### ISSUE TITLE
Toggle for 'Tasks' text in widget

### ISSUE THREAD

**Issue by towo** [cinatic/taskwhisperer#45]
Since it's pretty obvious that I'm looking at my tasks when I see the TaskWarrior icon in front, I'd either recommend dropping the 'Tasks' suffix altogether when the icon is displayed, or make it an option to hide it.

**Comment by cinatic** [comment]
I like to have a bigger button, maybe because I have a ultra wide screen monitor.

So you would like to have only the number + icon?

**Comment by towo** [comment]
Totally okay with an option to just disable the text. :+1:
