### ISSUE TITLE
Filtering options

### ISSUE THREAD

**Issue by beatgammit** [cinatic/taskwhisperer#46]
I use tags a lot in my workflow where I have something like a "work" tag (e.g. a work context) and a "weekly" tag (stuff that needs to get done this week). I could get my desired result using a context or a custom filter, but neither seem to be available as options within TaskWhisperer.

The ["other" TaskWarrior extension](https://github.com/sgaraud/gnome-extension-taskwarrior) doesn't seem to be getting much attention, but that's really the main feature that's keeping me from switching to TaskWhisperer.

Perhaps this could be done by selecting how those tabs are determined? At home I use lots of projects, but at work I use mostly tags. I could probably submit a PR if this is something you'd be interested in doing.

**Comment by cinatic** [comment]
Hi @beatgammit,

thanks for the report, there is also another user which wants this  (#43) , and i also want to have this. So i will add it to the next release. But i will also be thankful if you want to provide something

Best regards
Florijan
