### ISSUE TITLE
Tasks not loading

### ISSUE THREAD

**Issue by kristoferobin** [cinatic/taskwhisperer#50]
Empty task list in extension,
command task rc.json.array=on status:Pending export
[
{"id":1,"description":"(bw)Is#2183
returns 53 entries

In lastlog after alt+f2 r have 3 entries of:
gnome-session[2039]: Gjs-Message: JS WARNING: [/home/kristof/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/convenience.js 209]: function getBestTimeAbbreviation does not always return a value

Gnome version
<?xml version="1.0" encoding="UTF-8"?>
<gnome-version>
 <platform>3</platform>
 <minor>18</minor>
 <micro>2</micro>
 <distributor>Ubuntu</distributor>

**Comment by cinatic** [comment]
Hi,

i think the warning can be ignored if undefined is returned nothing will break.

1. Please check if there are some other errors, if there is an fatal JS exception the extension would not be loaded or you can see it in ALT+F2 - > lg + enter -> Click on Show Errors for the extension
2. Is gnome-extension using the same user to fetch the tasks? You can verify this by creating a task inside the extension
3. can you provide at least one complete entry or send me the full output to florijanh[at]gmail.com

**Comment by kristoferobin** [comment]
1) Alt+F2 no errors
2) Even if I create new task via extension it didn't shown in extension, but I able to acces it via console
3) Sure, sent you full output to email

EDIT
I created "id":54 via extension, but it didn't shown in it, still empty

**Comment by cinatic** [comment]
Thanks, that's a lot of output I noticed that when there is too much
console output GIO.subprocess will cut it and then it can not be parsed
anymore. You can verify if you are affected by cleaning all tasks or
replace the command in taskservice.js to fetch only one/few items.

kristoferobin <notifications@github.com> schrieb am Do., 8. Feb. 2018,
12:26:

**Comment by kristoferobin** [comment]
Yep, after I executed task done 54 I'm now able to see it in Done section in extension

**Comment by cinatic** [comment]
okay thanks for the verification, i need to check how i can solve this issue

**Comment by cinatic** [comment]
i fixed it in the last commit by replacing it with Glib 44b91d196daa2641518e1151512791ccc9ca4fb6.

I really need to cleanup the whole code sometime
