### ISSUE TITLE
Not working with gnome-shell 3.32

### ISSUE THREAD

**Issue by taurthil** [cinatic/taskwhisperer#56]
Problem with loading module in Arch linux gnome shell 3.32

**Comment by cinatic** [comment]
hi, i changed the es6 parts accordingly in 53f10078437f9c16911cd4d5f9099273653689ba, let me know if there are still issues

**Comment by grandfso** [comment]
@cinatic I'm on Gnome 3.32.Installed the extension from github. It appears to be working, but the configuration of the extension does not open.
https://i.imgur.com/T77utpj.png

Technical details: 
```
TypeError: can't convert undefined to object

Stack trace:
  _init@/home/user/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/prefs.js:35:21
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/prefs.js:253:18
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
  main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
  @<main>:1:43
```

**Comment by ghost** [comment]
whoops did not tested the settings, it should be fine now, thanks for the input

**Comment by grandfso** [comment]
@cinatic Thanks for the quick fix. The config now opens without issues.
I think I've found another thing - the icon does not show up in the top bar: https://i.imgur.com/cQhlOIt.png

When changing the setting 'show icon in panel' on and off, I can see there is space allocated for the icon, but it is not being displayed.

**Comment by ghost** [comment]
ah right there is this icon in the panel i create another bug task for that
