### ISSUE TITLE
Error loading extension on Ubuntu 18.10 Gnome 3.30.2

### ISSUE THREAD

**Issue by dregimbal** [cinatic/taskwhisperer#60]
Installing the extension from https://extensions.gnome.org/extension/1039/taskwhisperer/ or locally via a git pull doesn't work.
Looking glass (alt+f2, lg) shows the following error
`TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)`

**Comment by cinatic** [comment]
Hm interesting you should get from EGO the version without the changes for 3.32.

Is the error message the same as when you  install it from EGO?

Finally if the EGO version does not work, please try the previous version 

https://github.com/cinatic/taskwhisperer/releases/tag/v11_1

**Comment by cinatic** [comment]
Should be fixed b y last version
