### ISSUE TITLE
unable to scroll in PopupSubMenu

### ISSUE THREAD

**Issue by smoebody** [cinatic/taskwhisperer#63]
> ..., there is still a really tiny thing with scrolling due of the ScrollView inside the PopupSubMenu, scrolling stops when cursor is inside a submenu. I will fix this later by creating a own Menu Object.

_Originally posted by @cinatic in https://github.com/cinatic/taskwhisperer/issues/15#issuecomment-210964718_

As stated here it is not possible to scroll in an opened task. sometimes this is necessary, i.e. when the task-details contain more than the Popup can show. This prevents me from getting to the start-button.

I wanted to make aware of this. 

Thanks for the extension. Much appreciated.

**Comment by cinatic** [comment]
thanks for the feedback, could you share a screenshot?

**Comment by smoebody** [comment]
@cinatic sorry, i am not using taskwarrior or taskwhisperer anymore.
