### ISSUE TITLE
Not Working in GNOME Shell 3.36.0

### ISSUE THREAD

**Issue by LaurentOngaro** [cinatic/taskwhisperer#68]
The extension can be loaded and its settings can be edited, but there is no icon in the gnome panel.

This is the issue I can see in the gnome shell log:

`mars 14 11:02:08 BigDaddyArco gnome-shell[1540]: JS ERROR: TypeError: this.headerBar is undefined
                                                 checkPanelControls@/home/laurent/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:843:9
                                                 loadSettings/this._settingsC<@/home/laurent/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:993:18
mars 14 11:02:10 BigDaddyArco gnome-shell[1540]: Usage of object.actor is deprecated for TaskWhispererMenuButton
                                                 get@resource:///org/gnome/shell/ui/environment.js:285:29
                                                 checkPositionInPanel@/home/laurent/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:856:21
                                                 loadSettings/this._settingsC<@/home/laurent/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:992:18
mars 14 11:02:10 BigDaddyArco gnome-shell[1540]: Attempting to remove actor of type 'Gjs_taskwhisperer-extension_infinicode_de_extension_TaskWhispererMenuButton' from group of class 'StBoxLayout', but the container is not the actor's parent.
mars 14 11:02:10 BigDaddyArco gnome-shell[1540]: Usage of object.actor is deprecated for TaskWhispererMenuButton
                                                 get@resource:///org/gnome/shell/ui/environment.js:285:29
                                                 checkPositionInPanel@/home/laurent/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:864:21
                                                 loadSettings/this._settingsC<@/home/laurent/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:992:18
mars 14 11:02:10 BigDaddyArco gnome-shell[1540]: clutter_actor_insert_child_at_index: assertion 'child->priv->parent == NULL' failed
mars 14 11:02:10 BigDaddyArco gnome-shell[1540]: JS ERROR: TypeError: this.headerBar is undefined
                                                 checkPanelControls@/home/laurent/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:843:9
                                                 loadSettings/this._settingsC<@/home/laurent/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:993:18
mars 14 11:05:22 BigDaddyArco gnome-shell[1540]: JS WARNING: [resource:///org/gnome/shell/misc/extensionUtils.js 196]: reference to undefined property "metadata"
`

**Comment by cinatic** [comment]
should be fixed with the upcoming release, you can test it by cloning or using this https://github.com/cinatic/taskwhisperer/suites/530265458/artifacts/3076267

**Comment by LaurentOngaro** [comment]
It works. Many thanks !!!
