### ISSUE TITLE
loading tasks failed

### ISSUE THREAD

**Issue by HeikoAdams** [cinatic/taskwhisperer#7]
I've created some tasks and now the extension fails on loading my task list.

gnome-logs lists the following errors:

> (gnome-shell:23486): Gjs-WARNING **: JS ERROR: TypeError: a.Due is undefined
> 
> TaskWhispererMenuButton<.reloadTaskData/</<@/home/heiko/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:221
> 
> TaskWhispererMenuButton<.reloadTaskData/<@/home/heiko/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/extension.js:219
> 
> readCB@/home/heiko/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/taskService.js:128

**Comment by HeikoAdams** [comment]
Addition: Some of the tasks I've created didn't have a due-date but to workaround this issue I've set a due-date to the end of the year for that tasks.

**Comment by cinatic** [comment]
fixed in master
