### ISSUE TITLE
Solving the lack of documentation

### ISSUE THREAD

**Issue by psychoslave** [cinatic/taskwhisperer#70]
Hello,

First thank you for this extension, it seems very nice.

I fail however to find how to use it effectively. It would be great to have more documentation, especially:

- a section explaining what each icon at the top are for. The three first are most likely "add", "synchronize with server" and "parametrize". However I fail to grasp the meaning of the four others.
- how to filter by arbitrary tag: the extension seems to randomly takes three of them, but I see no obvious way to select for any other tag
- how to pop up the menu with a keyboard shortcut

The two later might be non-existent features, in which case I'll gladly open two other issues for requesting them

Thanks again for the work so far.

**Comment by cinatic** [comment]
you never know until you try
