### ISSUE TITLE
Something happened with the base theme.

### ISSUE THREAD

**Issue by k1ll1n** [cinatic/taskwhisperer#74]
base theme
![base_theme](https://user-images.githubusercontent.com/4102348/82528207-76c5db80-9b62-11ea-9a33-753a56f3bce2.jpg)

alternative theme
![alternative_theme](https://user-images.githubusercontent.com/4102348/82528238-834a3400-9b62-11ea-9707-2f3a411ab01b.jpg)

For some reason, my popup is just a little bit like yours

![yours_screenshot](https://github.com/cinatic/taskwhisperer/raw/master/images/menu.png)

How can I make the same window as yours?

**Comment by cinatic** [comment]
The styling is not well implemented yet, I will try to focus on a proper theme support in the next version. Which themes are you using for gtk and shell?

**Comment by kevinoliveira** [comment]
i had the same issue here, i'm on ubuntu 20.04 using the default theme, here is how i solved:

1. install [gnome-tweak-tools](https://itsubuntu.com/install-gnome-tweak-tool-on-ubuntu-20-04/)
2. install gnome [user-themes extension](https://extensions.gnome.org/extension/19/user-themes/)
3. open gnome-tweak-tools, navigate to appearance and change your shell theme
