### ISSUE TITLE
Failed to load tasks after adding a task in CLI

### ISSUE THREAD

**Issue by Chouchen** [cinatic/taskwhisperer#8]
I'm on GnUbuntu 15.10.
I installed taskwarrior and added a test task.
Then I installed this plugin and no task were listed.
I tried to add a task with this plugin and no task listed by this way either.
Gnome shell logs told me this : `(gnome-shell:1916): Gjs-WARNING **: JS ERROR: TypeError: taskListData.map is not a function`

I looked at all *.data file in ~/.task and it seems taskwarrior put task in JS object but those objects aren't in an array.
BTW, all tasks were there (from task CLI and from the plugin)

So I modified taskService.js like this 

```
shellProc.wait_async(null, function(obj, result)
        {
            let shellProcExited = true;
            shellProc.wait_finish(result);
            let buffer = "[";
            var stream;

            function readCB(obj, result)
            {
                var bytes = stream.read_bytes_finish(result);

                if(!bytes.get_size())
                {
                    buffer = buffer.toString();
                    buffer = buffer+"]";
                    global.log(buffer);
                    let taskListData = JSON.parse(buffer);
                    let taskList = taskListData.map(function(taskData, index, data)
                    {   
                        return new Task(taskData);
                    });

                    onDataLoaded(taskList);
                }
                else
                {
                    buffer = buffer + bytes.get_data();
                    stream.read_bytes_async(8192, 1, null, readCB);
                }
            }

            stream = shellProc.get_stdout_pipe();
            stream.read_bytes_async(8192, 1, null, readCB);
        });

```

Adding the `[` and `]` it needed.

Reloading Gnome shell and it worked.

Is it normal?

**Comment by Chouchen** [comment]
Actually, it doesn't work with more than one task with this patch.

I made it work with this ugly line instead `buffer = "["+buffer.toString().replace(/\}/gi, '},').slice(0,-2)+"]";` where it was `buffer = buffer.toString();`

**Comment by cinatic** [comment]
hmm, could you please show me the output of:

`task status:Pending export`

in your terminal?

**Comment by Chouchen** [comment]
Sure

```
{"id":1,"description":"desc","due":"20160215T230000Z","entry":"20160217T100838Z","modified":"20160217T100838Z","project":"test","status":"pending","uuid":"4c6abf30-6bbf-4733-87f8-5da8ed2199a1","urgency":10.5307}
{"id":2,"description":"desc2","due":"20160216T230000Z","entry":"20160217T111209Z","modified":"20160217T111209Z","project":"test2","status":"pending","uuid":"6a2f51a8-cea1-4a5c-976b-aad6f863df46","urgency":10.0735}
```

**Comment by cinatic** [comment]
i think i found the difference.

can you please add this in your ~/.taskrc
json.array=on

or if this doesn't work execute this in the terminal and check if then the JSON is valid

task status:Pending export rc.json.array=on

**Comment by Chouchen** [comment]
Adding `json.array=on` made it works :+1: 
Thanks, that should be written somewhere :)

**Comment by cinatic** [comment]
Yep you are right, thanks for the further information
