### ISSUE TITLE
Can't install on gnome 41 via extensions.gnome.org.

### ISSUE THREAD

**Issue by ZephOne** [cinatic/taskwhisperer#98]
OS: Debian sid
Gnome version 41

![taskwhisperer_gnome_extension_not_compatible](https://user-images.githubusercontent.com/25317904/142172362-f4ab985c-eafd-4fb1-a01e-f06624a5ec7a.png)

Is there something to do like :
```diff
diff --git a/taskwhisperer-extension@infinicode.de/metadata.json b/taskwhisperer-extension@infinicode.de/metadata.json
index 2f1471c..52ba2ec 100644
--- a/taskwhisperer-extension@infinicode.de/metadata.json
+++ b/taskwhisperer-extension@infinicode.de/metadata.json
@@ -6,9 +6,10 @@
     "3.32",
     "3.36",
     "3.38",
-    "40"
+    "40",
+    "41"
   ],
   "url": "https://github.com/cinatic/taskwhisperer",
   "uuid": "taskwhisperer-extension@infinicode.de",
-  "version": 20
+  "version": 21
 }
```
Or is a bit more complex ?

**Comment by svenuthe** [comment]
Yes it is as easy as it.
You can even modify the file in your local installation probably at `~/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/`.

**Comment by ZephOne** [comment]
@svenuthe sorry, didn't see your answer. Anyway, thanks for it. And also thanks for having done the pull request, hoping it will be merge.
