### ISSUE TITLE
Documentation doesn't say it needs Graphene

### ISSUE THREAD

**Issue by ebaudrez** [cinatic/taskwhisperer#99]
Hi there, the extension requires Graphene, but the documentation doesn't say that (neither in https://github.com/cinatic/taskwhisperer/blob/master/README.md nor in https://extensions.gnome.org/extension/1039/taskwhisperer/). It was easy enough to figure it out using Looking Glass, but I wouldn't expect every user to know about it (I didn't before I started troubleshooting :).

Kind regards!

**Comment by cinatic** [comment]
Hi & thanks for the report,

i always thought graphene is a bounded part of gnome as the shipped UI has several dependencies to graphene 

https://gitlab.gnome.org/search?search=graphene&group_id=8&project_id=546&scope=&search_code=true&snippets=false&repository_ref=main&nav_source=navbar

i use graphen only for a fade effect in the list view and which is in fact not even enabled in the released build (i always wanted to add it as a settings, but i am super lazy), i can implement it differently if this matters for you. 

Can you elaborate how it comes that you do not use graphene?

**Comment by ebaudrez** [comment]
Hello, thanks for replying. i don't know why, but on openSUSE Leap (both 15.2 and the latest official release, 15.3) `typelib-1_0-Graphene` doesn't appear to be a required component. I can remove `typelib-1_0-Graphene-1_0` without breaking any dependencies on a Gnome desktop. The base library `libgraphene-1_0-0` *is* required by `gstreamer-plugins-base`, though, but without the `typelib`, the plugin won't work.

**Comment by cinatic** [comment]
okay, that is interesting. tbh i have only a rough understanding of that. But it seems it could affect a lot of other users as well, so i will think about a solution

**Comment by ebaudrez** [comment]
tbh the easy way out is to adapt the documentation. [this extension](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet) does just that in the section [Prerequisites](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet#prerequisites).
